basePath: /
definitions:
  model.Pulse:
    properties:
      product_sku:
        type: string
      tenant:
        type: string
      timestamp:
        type: string
      use_unit:
        type: string
      used_amount:
        type: number
    required:
    - product_sku
    - tenant
    - use_unit
    - used_amount
    type: object
  service.AggregatedPulseDTO:
    properties:
      product_sku:
        type: string
      tenant:
        type: string
      total_used:
        type: number
      use_unit:
        type: string
    type: object
info:
  contact: {}
  description: API for usage pulse ingestion and aggregation.
  title: Cloud Metering Ingestor API
  version: "1.0"
paths:
  /aggregates:
    get:
      description: Returns current aggregation grouped by tenant, SKU and unit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.AggregatedPulseDTO'
            type: array
      summary: Get aggregated usage data
      tags:
      - pulses
  /flush:
    post:
      description: Simulates sending the aggregated data and clears current state
      responses:
        "200":
          description: Flushed
          schema:
            type: string
      summary: Flush current aggregated data
      tags:
      - pulses
  /pulses:
    post:
      consumes:
      - application/json
      description: Accepts a usage pulse and adds it to the aggregation service
      parameters:
      - description: Usage Pulse Data
        in: body
        name: pulse
        required: true
        schema:
          $ref: '#/definitions/model.Pulse'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Receive a new usage pulse
      tags:
      - pulses
swagger: "2.0"
